### ISSUE TITLE
Users aren't added to admin group when installing to unbooted 10.10 system

### ISSUE THREAD

**Issue by kbotnen** [MagerValp/CreateUserPkg#38]
Test and verify if the administrative users still works on yosemite 10.10.

This is a task to be carried out, not a bug.

It seems that administrative users created with a version 1.2(41) is installed as normal user in 10.10.

Will try to update createuserpkg to 1.2.4(58), reimage and reinstall the user to see if it works as expceted.

If it still does not work, Ill try to isolate based on which type of image is used (os version).

**Comment by photogeis** [comment]
I had this issue as well with 1.2.4 applied after the 10.10 OS (non booted image created with AutoDMG) in Casper Imaging. I then moved install of admin account to after reboot and the admin account worked as expected.

**Comment by marmehlad** [comment]
I´ve had  a similar problem when creating an admin-user, user was created with no admin-rights. 
Since I skipped Apples setup-form I ended up with one non admin user. 
Could I ask you MagerValp  witch user ID (ex 501) you're using?
