### ISSUE TITLE
Hidden Account Not Recognizing Password 

### ISSUE THREAD

**Issue by ghost** [MagerValp/CreateUserPkg#42]
Guys, after I've created a new UserCreatePkg hidden account, added it to casper then deployed my image (OS 10.9) to my test laptop, I can see that the account I've created after the machine reboots.  However, when I try using the password to authenticate against the account I've created, from the UserCreatePkg utility --the password will not allow me to login.  The account creation process is very straight forward, but I'm not sure what's preventing the account from recognizing the password that I built in the the UserCreatePkg utility.  

I'm puzzled. Am I missing a step?  Any thoughts or directions out there?

**Comment by MagerValp** [comment]
Have you tried installing the package through a policy rather than with Casper Imaging? Failing that, does it work if you install it manually on a system?

**Comment by unimachead** [comment]
Thanks, MagerValp...

I set a policy in place, but still no success.  So I've pulled a virgin factory image into place on a bare HD, created a temp admin act then once under the temp account I launched CreateUserPkg and created a standard primary admin account pkg. I decompressed the pkg, installed it and watched the magic happen. Afterwards I logged out of the temp admin account and logged in under the account I just built and installed with CreateUserPkg.  I then deleted the temporary account.  Now I have an admin standard.  So when the machine is bound to AD, I can then get our users to login via single-user sign on.  

it's not the way I thought CreateUserPkg was supposed to work outside of actually creating a another account to circumvent what should just happen through uploading a custom created pkg uploaded into Casper.

**Comment by MagerValp** [comment]
I'm not quite sure what you mean by decompressing the pkg, and AD binding is another variable that wasn't mentioned, but the point is that the package works fine when installed manually but not when installed with Casper. The question is in what way the installs differ.

Does the account show up under /Local/Default/Users in dscl? Can you successfully authenticate using dscl authonly? What happens if you use login adminname in a Terminal?
