### ISSUE TITLE
Not updating existing user's FileVault password

### ISSUE THREAD

**Issue by tincansandtwine** [MagerValp/CreateUserPkg#43]
I'm trying to use createuserpkg as a tool to update the local admin password, and while it does work to change the login password, the FileVault password does not get updated. Reproduced the issue several times on different machines. Here are my steps:

Machine imaged
Account created (with old password) via munki with createuserpkg
Issue new pkg via munki (created with createuserpkg)
Old password still used for FileVault, but new password required to log in

Running this on 10.10.3 machines. If this isn't the intended usage of createuserpkg, I'm open to other ideas. I was able to change the password using

dscl . -passwd /Users/<user> <oldpass> <newpass>

but that puts both the passwords in plaintext.

Thanks!

**Comment by MagerValp** [comment]
To the best of my knowledge it's not possible to update the FV2 password without physical access or sending it in plain text. The best workaround I've found is to update the account password with CUP, and have the login window update the preboot password on the next login. Until then the machine has to be unlocked with the old password.
