### ISSUE TITLE
Additional options

### ISSUE THREAD

**Issue by dwgeddes** [MagerValp/CreateUserPkg#45]
This tool is very helpful, but here are some additional options I'd love to see:

* To have the package check if the account exists.  If it exists, the choice to either do nothing or update the current user-- to match the packages password, account picture, display name, and account type, but keeping the current unique identifiers.  Or if you update the identifiers, to also update the permissions and whatnot so it doesn't break the user account.
* The option to not specify a User ID, but to have the new user account just pick the next available ID
* The option to also enable the user in Filevault, if Filevault is already enabled on the boot drive.

Sorry if you'd prefer these each be in separate issues.  I can break them out if you'd like, but I'm not sure which is better etiquette.

**Comment by MagerValp** [comment]
Even though they're all good suggestions I'm afraid I'm going to have to shoot them down. Partially updating an existing account is outside the scope of the package, it's not meant for interaction but for for silent deployment. Finding the next available ID would be very useful, but it goes against the "no moving parts" design of the package, where it just drops a plist payload. FileVault support would also be nice, and while I won't add direct support for it you could add it to a custom postflight script if issue #18 gets done.
