### ISSUE TITLE
Doesn't work when pass is 16 characters in length

### ISSUE THREAD

**Issue by jmprice18** [MagerValp/CreateUserPkg#46]
When entering a password that is mixed alphanumeric, the account's password is incorrect.  I've tried this 5 times when different username and password combinations.

**Comment by MagerValp** [comment]
I'm afraid I can't reproduce that. I created a user with login `testuser` and password `abcd1234ABCD1234` and it can log in successfully. What are the other values, e.g. uid, homedir, and uuid?
