### ISSUE TITLE
Incorrect system file permissions in 10.11.x

### ISSUE THREAD

**Issue by mortopc4** [MagerValp/CreateUserPkg#49]
After creating the new user and booting to the user, system folders such as Downloads have a red minus on them and indicate that the "folder cannot be opened because you do not have permissions to see the contents."

Although this can be fixed manually, is there a way to fix this through the application?

Cheers!

**Comment by MagerValp** [comment]
CreateUserPkg does not create the home directory, it's typically created automatically on first login by the system. So I guess the question is how was the home directory created, and who exactly owns them if not the newly logged in user?

**Comment by kyleericson** [comment]
Having a user library needs to be repaired when logging in for the first time with this user Os 10.11.3+

**Comment by jreitzersmith** [comment]
I get the "user library needs to be repaired" issue on 10.11.3 as well. I
have not used the packages on prior 10.11 revisions, so I cannot confirm
whether this issue is specifically 10.11.3 or 10.11 in general.

**Comment by MagerValp** [comment]
Please post a screenshot of your CreateUserPkg settings, and the output of `ls -al` and `df -h ~` (without repairing the library).

**Comment by marrkkuu** [comment]
I've seen this before on different OS versions but mainly when upgrading an
OS and retaining an existing user home. And this is on systems that don't
use CreateUserPkg.

The fix I implemented although lazy does work, and that was to delete the
user Keychains folder.

**Comment by jreitzersmith** [comment]
I'm not certain if the pictures will show up here since I'm responding via
email:

CreateUserPKG settings:

[image: Inline image 1]

before login (from another account):

[image: Inline image 2]

after login:
[image: Inline image 3]

Please let me know if the pictures are not included and if there's anything
else that I can provide.

Regards,
John Reitzer-Smith

**Comment by MagerValp** [comment]
I think that's a nope on the attachments :) Either post on github or maybe post links? The important part is the output of `ls -al` and `df -h ~` though.

**Comment by jreitzersmith** [comment]
Per, I've updated my previous comment with the screenshots.

**Comment by MagerValp** [comment]
It looks like the home directory was created by the Citrix Receiver installer, and not on first login by the OS. Try without without it.

**Comment by kyleericson** [comment]
I still have this issue. How do I fix this? on 10.11.3+

**Comment by MagerValp** [comment]
Most likely by removing the offending package from your workflow.

**Comment by kyleericson** [comment]
I did try to run it by it self and it seems to work so must be a MDM issue.
