### ISSUE TITLE
App didn't work in recovery environment 

### ISSUE THREAD

**Issue by kevintruong** [MagerValp/CreateUserPkg#53]
Hi MagerValp. 
The utility tool is really helpful for me. But have a tiny issue. 
I want the application is working in recovery environment (I customized the OS recovery for my self) . 
I also understand the tool dependency in Python (also add Python2.7 to my customized OSX recovery). But the app still didn't working. 
The error return is kill 9. 
I have know idea about the issue. 
Will take time to take a look into the issue in Recovery Environment. 
But I think I will need your advice. 
Thanks and best regards, 
Kevin

**Comment by MagerValp** [comment]
Recovery mode doesn't support general applications, so it's no suprise that CUP doesn't work - most likely it's missing some system framework. Closing as wontfix, as I consider this expected behavior rather than a bug.
