### ISSUE TITLE
Tick Box to also generate a package which may be used to delete the user.

### ISSUE THREAD

**Issue by henri** [MagerValp/CreateUserPkg#56]
I suppose it is easy enough to change the password or remove the user with a script. But it would be neat to also have the support for removal of a user and possibly even the home directory?

If this is something which you think could be useful. I will work on a patch and issue a pull request. I would only do this if you think there is a good chance of it being incorporated.

**Comment by MagerValp** [comment]
Hi, as you say this could easily be solved with a script, in a [payload free package](https://github.com/rtrouton/Payload-Free-Package-Creator). It also kinda goes against the whole name of the app :) So thank you, but I think not.
